### ISSUE TITLE
list_report can fail if no 3rd argument

### ISSUE THREAD

**Issue by jonorthwash** [goavki/phenny#131]
Fix Line 137 of `mailing_list.py` (https://github.com/goavki/phenny/commit/d0246c22a9e058403a8d4355be4d7cfe911e7b64#diff-83eb0c0023d4524d35045cd0e95a6b01R137) so that it behaves correctly if there are 3 groups.

**Comment by Androbin** [comment]
> if there's no group 3 this crashes

Shouldn't `group(3)` simply be `None`?
Could you provide further details on the "crash"?

**Comment by jonorthwash** [comment]
I think it's because `input` doesn't isn't guaranteed to have more than 3 groups.  If it has e.g., only 2 groups and you do `.group(3)`, then it does not return `None` and instead crashes.

**Comment by Androbin** [comment]
Isn't `group` supposed to be set to `match.group` ?

**Comment by jonorthwash** [comment]
> Isn't `group` supposed to be set to `match.group` ?

I'm not sure there's a variable named `group` in there.

**Comment by Androbin** [comment]
I was referring to the following lines:
https://github.com/goavki/phenny/blob/master/bot.py#L189
https://github.com/goavki/phenny/blob/master/bot.py#L229

**Comment by jonorthwash** [comment]
Yes, but that's still a match object, and will crash instead of returning `None`.  Right?

**Comment by Androbin** [comment]
Well, the documentation says that `match.group` should return `None` here:
https://docs.python.org/3/library/re.html#re.match.group

I don't get why this would crash here.

**Comment by jonorthwash** [comment]
It does?  I see the following:

> If a group number is negative or larger than the number of groups defined in the pattern, an `IndexError` exception is raised.

**Comment by Androbin** [comment]
But this refers to the number of groups in the pattern, not the number of groups matched.

**Comment by jonorthwash** [comment]
Okay.  Can you try to reproduce the failure?  I may have the reasoning wrong, but what I did did prevent the code from failing at that point.

**Comment by Androbin** [comment]
Gimme a moment. I'll try.
