### ISSUE TITLE
github comment trimming

### ISSUE THREAD

**Issue by jonorthwash** [goavki/phenny#132]
Have long comments trimmed to message length instead of allowing them to be sent as multiple messages.

For example, the following should only have returned the first message, with "..." or similar at the end:

> `(04:34:20) begiak: apertium-html-tools: jonorthwash * new comment on issue #12: From https://sourceforge.net/p/apertium/tickets/6/> This is the interface code from GCI2013:> https://github.com/Dan12/Dan12.github.io/tree/master/google_code_in/spell_checker_interface> It's pretty slick, but needs to be integrated into html-tools.In fact, a mostly working version has already been implemented, just is disabled by default because the`
> `(04:34:25) begiak: backend doesn't work.  See work done during GCI2014:* [HTML-TOOLS SPELL-CHECKER INTERFACE](https://www.google-melange.com/gci/task/view/google/gci2014/5892261774622720)Related tasks:* [MAKE VOIKKOSPELL UNDERSTAND APERTIUM STREAM FORMAT INPUT](https://www.google-melange.com/gci/task/view/google/gci2014/5895320328208384)* [MAKE VOIKKOSPELL RETURN OUTPUT IN APERTIUM STREAM`
> `(04:34:29) begiak: FORMAT](https://www.google-melange.com/gci/task/view/google/gci2014/5799415050665984)* [LIBVOIKKO SUPPORT FOR APY](https://www.google-melange.com/gci/task/view/google/gci2014/6137916455649280) https://github.com/goavki/apertium-html-tools/issues/12`

**Comment by shardulc** [comment]
Is this just for comments on issues, all sorts of comments, or all messages whatsoever having a human-entered field (like commit messages)?

**Comment by jonorthwash** [comment]
I mean, I guess the formatting for issues comments needs work.  We have `.more` as a more general solution, but I don't think it's the best (or at least, first) way to approach this.

**Comment by wei2912** [comment]
`.more` should not the approach used, as it should (and can) only be used for user queries. Trimming the comment as @shardulc has done is probably the best solution. Full comments can be accessed via the link.

**Comment by jonorthwash** [comment]
A trimmed version was the idea.  These are just channel notifications, not intended as a full replacement interface for github.  Perhaps we should have a simple function accessible to various modules that accepts chunks of text and assembles them into a single message, triming the chunks it's been told to keeping the whole thing within normal message length.
