### ISSUE TITLE
Weird output from begiak's email module

### ISSUE THREAD

**Issue by svineet** [goavki/phenny#155]
begiak
apertium-contact: Kevin Brubeck Unhammer un...@mm....st: Re: [Apertium-contact] =?utf-8?q?Apertium_har_sluttet_=C3=A5_virke_p?= =?utf-8?q?=C3=A5_PC=27en_min!?= 
apertium-contact: Kevin Brubeck Unhammer un...@mm....st: Re: =?utf-8?q?oversettelse_g=C3=A5r_ikke?=

maybe begiak should ignore urls in emails and print the actual text?

**Comment by unhammer** [comment]
they're not urls, that's email encoding of unicode stuff (e.g. å turns into =C3=A5)

**Comment by shardulc** [comment]
Duplicate of #260.
