### ISSUE TITLE
Begiak is too strict about nick capitalization

### ISSUE THREAD

**Issue by ghost** [goavki/phenny#158]
It would be great if Begiak would read the messages out to those nicks which it also informs that they have unread messages:

<Testing12340202> begiak, tell putti something
<begiak> Testing12340202: I'll pass that on when putti is around.

Joining the channel with nick "Putti"
<begiak> Putti: You have messages. Say something, and I'll read them out.
<Putti> something
--> Begiak not reading out the messages

/nick putti
<putti> something
<begiak> putti: 11:24Z <Testing12340202> tell putti something
--> works now when the nick written with lower case p

**Comment by unhammer** [comment]
I also once tried "Begiak, tell nick something" and it didn't respond until I tried "begiak, tell nick something"

**Comment by jonorthwash** [comment]
I don't think we want to have begiak respond to Begiak.  What's the consensus on this?

**Comment by sushain97** [comment]
I’m fine with Begiak == begiak. However, I’m not as certain about Putti == putti.

**Comment by wei2912** [comment]
As far as I know, IRC nicknames are not case sensitive, so it shouldn't be
an issue to implement this.

**Comment by unhammer** [comment]
Yeah, on IRC, `"Putti" == "putti"`. 

Nicks should be *stored* in original form wherever stored, but any comparison should be case-insensitive.

**Comment by jonorthwash** [comment]
Begiak == begiak will be harder to implement because of how the bot is written, but I guess it could be done...

**Comment by wei2912** [comment]
@vikramkashyap Any fix to this issue should cover the whole bot, not just the `tell` module.

**Comment by vikramkashyap** [comment]
@wei2912 I understand. So would a complete solution to this issue be to modify all instances of comparisons of nicks in the bot to make them case-insensitive?

**Comment by wei2912** [comment]
Yes, you got that. I'd suggest you check if Python has such a function for
case insensitive comparison of two strings. If not, create a function for
it and make the modules use it.

**Comment by unhammer** [comment]
This is the Python3 way to do case-insensitive comparisons:
```
>>> "AÐ".casefold() == "að".casefold()
True
```

It's unicode-aware, in case you ever run phenny on an irc server that allows non-ascii nicks…:
```
>>> "BUSSE".casefold() == "Buße".casefold()
True
```
