### ISSUE TITLE
.time does not show correct time

### ISSUE THREAD

**Issue by svineet** [goavki/phenny#169]
`.time IST` gives time that is -3 hours off. `.time GMT` gives time that is -13 hours off.

IST should be +0530 but by begiak's .time command it seems to be +1000.

**Comment by svineet** [comment]
`.time UTC' returns correct time. As TinoDidriksen suggested it might be that IST means something else, like Israel Standard Time, etc. But GMT still seems to be off and that is strange.

**Comment by vigneshv59** [comment]
.time GMT works as well.

**Comment by vigneshv59** [comment]
Fixed with https://github.com/goavki/phenny/pull/171
