### ISSUE TITLE
git/svn stuff should be channel-specific

### ISSUE THREAD

**Issue by unhammer** [goavki/phenny#174]
I'm guessing people who are in #hfst (and not #apertium) don't care much about commits (or long-winding issue reports like this) to apertium-html-tools; could they be made channel-specific?

**Comment by flammie** [comment]
That would be a good thing, please. If it is difficult to implement I can maybe look at it if I know what to look at?

**Comment by unhammer** [comment]
Here's a workaround for Weechat users at least: `/filter add begiak-apertiumcia-in-hfst *.#hfst nick_begiak (?-i)^apertium:`

**Comment by jonorthwash** [comment]
I think this is resolved now?

**Comment by flammie** [comment]
I guess the implementation is fixed, however, the settings are still missing, now omorfi commits for example go to all channels and hfst seems to go to apertium too, but not vice versa.

**Comment by unhammer** [comment]
goavki-stuff is still showing on #hfst and #matxin too

**Comment by jonorthwash** [comment]
Config updated.  If everything works as it's supposed to, goavki updates should only go to #apertium, and hfst updates should only go to #hfst.

**Comment by jonorthwash** [comment]
Hmm, okay, that does not seem to be the case.  I have this config parameter set:
`git_channels = {'goavki': ['#apertium'], 'hfst': ['#hfst']}`

But it seems the code is not in place ot make that work, or is potentially buggy.

**Comment by unhammer** [comment]
How about we have one channel as "default" if a repo is not specified in git_channels? E.g. 
` git_channels = {'*': ['#apertium'], 'hfst': ['#hfst']}` would make everything go to `#apertium` except stuff from https://github.com/hfst/hfst/

**Comment by Androbin** [comment]
Is this issue still up-to-date?

**Comment by jonorthwash** [comment]
The level of control is still not what would be ideal, I believe.

**Comment by jonorthwash** [comment]
Though perhaps it's okay—we just have to specify per-channel repos.  Why don't you investigate? :)

**Comment by Androbin** [comment]
We already have `git_channels` to control which channels to post to.
Maybe we could extend the configuration scheme of #275 to include non-branches?

**Comment by jonorthwash** [comment]
This is what the list currently is:
```
git_channels = {'apertium-html-tools':['#apertium'], 'apertium-apy': ['#apertium'], 'bootstrap':['#apertium'], 'hfst': ['#hfst'], 'ud-annotatrix': ['#_u-dep']}
```
My impression is that it works as expected.  @unhammer , is this not the case?

**Comment by jonorthwash** [comment]
I think e.g. `omorfi` commits get posted everywhere?  So the behaviour is similar to what is being suggested too?

**Comment by Androbin** [comment]
* Commits on branches and/or forks are only ever posted to `phenny.config.branch_channels[repo_fullname][ref]` (if such exists)
* Commits on `'refs/heads/master'` are posted to `phenny.config.git_channels[repo]` if such exists and to `self.phenny.config.channels` if not

**Comment by flammie** [comment]
Is this integrated now? I switched omorfi webhook back on to deliver the messages, but any push to a branch seems to come up as:
```
< begiak> Something went wrong: dict_keys(['pusher', 'ref', 'repository', 'sender', 'deleted', 'base_ref', 'after', 'before', 'compare', 
                'head_commit', 'commits', 'forced', 'created'])
```
(might also be unrelated / another bug)

**Comment by Androbin** [comment]
@flammie I think I provoked that issue, but it should be fixed in current `master`.

**Comment by jonorthwash** [comment]
`#apertium` is running latest master, and it seems to not be fixed.  We just got this:
> (00:49:11) begiak: Something went wrong: dict_keys(['pusher', 'before', 'forced', 'sender', 'compare', 'base_ref', 'after', 'organization', 'ref', 'commits', 'created', 'head_commit', 'deleted', 'repository'])

**Comment by jonorthwash** [comment]
I believe so.  At least, I haven't noticed anything like this for a little while.

**Comment by jonorthwash** [comment]
@flammie, @unhammer, is there any different functionality than what we currently have?  If so, just reopen the issue.

**Comment by jonorthwash** [comment]
We don't have wild-card support in the config, I think, but otherwise seems we have stuff going to the right places?
