### ISSUE TITLE
ignore merge commits?

### ISSUE THREAD

**Issue by unhammer** [goavki/phenny#182]
merge commits lead to lots of duplicate messages, can we ignore them? 

Alternatively, can begiak save the set of hashes reported per repo (at least save it in memory) and skip any already reported?

**Comment by Androbin** [comment]
How would we classify commits as "merge commits"?
* They contain or start with the word "merge" (nocase)
* They originate from a branch

The hash approach seems most promising.

**Comment by Androbin** [comment]
@shardulc What about this one?

**Comment by shardulc** [comment]
@sushain97 and I agreed that the best solution to this is to make squash commits while merging, instead of blocking the messages (it's a good practice anyway). I would suggest you work on #236 which kind of includes this issue.

**Comment by shardulc** [comment]
@Androbin Or, maybe #252 and the issues linked from it. Solving all of those in one go would be sufficient for a GCI task.

**Comment by Androbin** [comment]
I've decided to try #236 and look into other modules if things go well.

**Comment by Androbin** [comment]
@shardulc Shall we close this then?

**Comment by wei2912** [comment]
Certainly. I will close this issue.
