### ISSUE TITLE
skip repeating url titles so often

### ISSUE THREAD

**Issue by unhammer** [goavki/phenny#183]
how about a little cache [(url, timestamp)], say with max 5 members, fifo, for begiak's url title thing? That way we might skip repeating titles said within last N secs.

**Comment by SilentFlame** [comment]
Sounds cool to me.

would like to try, @unhammer  can you please guide as to what to do?

**Comment by unhammer** [comment]
I don't know the code-base. If I were to do this task, I would clone the repo and grep for things like "urllib" or "request" to find places where the url2title function might be defined.

**Comment by SilentFlame** [comment]
Ok cool, let me try that then. :)

**Comment by wei2912** [comment]
I'll be willing to guide you with the task. Just let me know if there are
any issues!

On Fri, 2 Dec 2016, 17:48 Vinay Singh <notifications@github.com> wrote:

Ok cool, let me try that then. :)

—
You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub
<https://github.com/goavki/phenny/issues/183#issuecomment-264414843>, or mute
the thread

**Comment by SilentFlame** [comment]
@wei2912 thanks a lot for that,

Let me once go through it and will ask you if stuck somewhere.

**Comment by wei2912** [comment]
@SilentFlame how is your progress?

**Comment by jonorthwash** [comment]
I don't understand what this issue is about.  Could someone summarise what the undesired behaviour is?

**Comment by unhammer** [comment]
Someone posts a link, begiak gives a summary. Someone refers to the same link two seconds later, begiak posts a summary again.  Someone starts doing hacks like "http foo[dot]com" to avoid begiak-spam.

**Comment by jonorthwash** [comment]
So begiak is making what already constitutes link spam a little worse?  I'm trying to understand when someone would post the same link over and over again to some reasonable end...

**Comment by unhammer** [comment]
@jonorthwash http://sprunge.us/cXIS is an example from a few minutes ago on #apertium

**Comment by jonorthwash** [comment]
I'm not sure I follow.  Could you share the relevant channel logs?

**Comment by unhammer** [comment]
Did the sprunge link not work? let me try a screenshot:
![begiak](https://user-images.githubusercontent.com/56868/33544447-1b02e4a6-d8db-11e7-9927-a49fafc72bdd.png)

**Comment by jonorthwash** [comment]
So is this issue about the buggy "posted" time, or about users sending the same urls unnecessarily often?

**Comment by sushain97** [comment]
I think Unhammer wants begiak to not repeat URL titles if they're repeated within e.g. 10 seconds.

**Comment by jonorthwash** [comment]
Hmm, I guess that could reduce IRC traffic by a line every now or then, but I'm not sure how often people are posting the same url over and over within a short time frame...  And the log @unhammer shared doesn't give me much sense of the time involved in that particular instance.

**Comment by unhammer** [comment]
> I think Unhammer wants begiak to not repeat URL titles if they're repeated within e.g. 10 seconds.

Yes, or even 300 secs …

**Comment by Androbin** [comment]
Quick clarification: Is this about the `head` modules `snarfuri` method?

**Comment by shardulc** [comment]
@Androbin Mostly, yes. I'm not sure but I think the Wikipedia module, maybe others, also use the posted database to check URLs; just to be sure, you should take a look.
