### ISSUE TITLE
Sourceforge issues plugin

### ISSUE THREAD

**Issue by frankier** [goavki/phenny#184]
Hi. The Sourceforge issue plugin #180 doesn't seem to be working on #apertium . It worked reasonably in my testing. Did you run into bugs and disable it? Is there something I can do to fix it?

**Comment by wei2912** [comment]
Seems to be related to https://github.com/goavki/phenny/issues/193.

**Comment by wei2912** [comment]
Fixed in a recent commit, but the polling functionality was removed.
