### ISSUE TITLE
.iso639 of 2-letter code should list related 3-letter codes

### ISSUE THREAD

**Issue by unhammer** [goavki/phenny#186]
```
<Unhammer> .iso639 lb                                                                       
<begiak> lb = Luxembourgish

```

but I wanted to know that the 3-letter code is "ltz"

**Comment by william1835** [comment]
Hi, I'm a GCI student, and I'm interested in doing this for my task.

**Comment by sushain97** [comment]
Hi @william1835. Please do! :)

**Comment by william1835** [comment]
Right, I think I've added this enhancement in the commit above. I think I'll do the opposite way round as well, so when three-letters codes are supplied, two-letter codes are given, then I'll create a PR for the changes

**Comment by jonorthwash** [comment]
@unhammer, is this fixed currently?

**Comment by unhammer** [comment]
```
Unhammer .iso639 lb        [10:12]
begiak lb, ltz = Luxembourgish
```
