### ISSUE TITLE
Slogans not working 

### ISSUE THREAD

**Issue by Putti** [goavki/phenny#187]
The example case explains it all:

\<Putti\> .slogan apertium
\<begiak\> AttributeError: 'NoneType' object has no attribute 'findall' (file "/home/begiak/phenny/web.py", line 43, in get)

Sounds like a nice feature – would be nice to get it working.

**Comment by Putti** [comment]
Seems like an easy fix: just check whether the 'head' got parsed or not. If not then return as in the other cases, otherwise proceed.

**Comment by jatinluthra14** [comment]
https://github.com/goavki/phenny/pull/191
Here it is.

**Comment by wei2912** [comment]
Merged in https://github.com/goavki/phenny/commit/88eed6ce6cddb4f9c7917e45de29ff92bd32db7f.
