### ISSUE TITLE
`sfissues` module not working

### ISSUE THREAD

**Issue by wei2912** [goavki/phenny#193]
When loading phenny, the `sfissues` module fails to load:

    Error loading sfissues: No module named 'feedparser' (in bot.py)

This is most likely because the module `feedparser` no longer exists. Could someone lookup when this module was removed and fix the module such that it no longer relies on `feedparser`? Thanks.

**Comment by jatinluthra14** [comment]
I'll work on this as a GCI task.

**Comment by jatinluthra14** [comment]
Fixed in this PR: https://github.com/goavki/phenny/pull/221
