### ISSUE TITLE
Begiak needs a build system that runs its tests

### ISSUE THREAD

**Issue by wei2912** [goavki/phenny#194]
Begiak needs a build system such as [Travis](https://travis-ci.org/). Upstream `phenny` has its own build system but no such system has been implemented for Begiak yet. Perhaps one could draw inspiration from the upstream build system and implement a similar system here?

**Comment by jatinluthra14** [comment]
I am trying this one.

**Comment by wei2912** [comment]
@jatinluthra14 has set up the build system on his fork. He is currently fixing the test suites which take a very long time to run, so that he can complete testing of the build system.

**Comment by jatinluthra14** [comment]
https://github.com/goavki/phenny/pull/214

**Comment by jatinluthra14** [comment]
https://github.com/goavki/phenny/pull/216 is merged. This issue can be closed.

**Comment by wei2912** [comment]
Not yet. We've yet to test the build system up on the main repository.

**Comment by jatinluthra14** [comment]
I think It's tested Or some tests are required?

**Comment by wei2912** [comment]
Yes, the build system is ready. Let me know when you've claimed the task.
