### ISSUE TITLE
set of tests not working

### ISSUE THREAD

**Issue by nuboro** [goavki/phenny#199]
There are some set of tests that are not working
test_head.py
test_mylife.py
test_rule34.py
test_search.py
test_tfw.py
test_vtluugwiki.py
test_weather.py
test_wiktionary.py

test_clock.py (runs 4 tests OK, but then takes a lot of time for the next(not sure if those works) )

**Comment by wei2912** [comment]
No need to run `test_rule34.py`, that module isn't used in the apertium channel anyways. Add the decorator:

```python
@unittest.skip("disabled module")
```

to the test file.

**Comment by jatinluthra14** [comment]
Fixed test_time taking lot of time in this PR https://github.com/goavki/phenny/pull/216

**Comment by wei2912** [comment]
To clarify, it wasn't a fix. The test was just disabled.

**Comment by shardulc** [comment]
I would like to work on this as a GCI task (https://codein.withgoogle.com/dashboard/task-instances/6277003982405632/). How many of the tests should I try to fix (through modifying the code or the tests)?

**Comment by wei2912** [comment]
@shardulc Try to fix all of them, most should be a few line fixes. If not, then inform us and skip the test. It can be dealt with later.

Check the build logs for an idea of what you need to fix.

**Comment by wei2912** [comment]
PR has been merged and all tests work now. Closing this issue.
