### ISSUE TITLE
Repeating "you have messages"

### ISSUE THREAD

**Issue by ghost** [goavki/phenny#209]
* nick (....) has joined
\<begiak\> nick: You have messages. Say something, and I'll read them out.
\<begiak\> nick: You have messages. Say something, and I'll read them out.
\<begiak\> nick: You have messages. Say something, and I'll read them out.

**Comment by Putti** [comment]
Oh, I see, it makes each one of these for every alias. Is that intended?

**Comment by Putti** [comment]
On another channel (#hfst, instead of #apertium) begiaks says following (happening at the same time):

* nick (...) has joined
\<begiak\> ...
\<begiak\> ...

**Comment by wei2912** [comment]
I don't understand the purpose of sending a message for every alias, given that only one nick is joining. https://github.com/goavki/phenny/blob/master/modules/tell.py#L279 is the LOC that causes this behaviour.

**Comment by Putti** [comment]
yeah, I would remove it

**Comment by jonorthwash** [comment]
When does this happen?
