### ISSUE TITLE
Magic number 430 used to represent maximum message length

### ISSUE THREAD

**Issue by wei2912** [goavki/phenny#213]
In many of begiak's modules, the constant 430 is used to represent the maximum message length, however its use can be confusing for code maintainers. I suggest that a constant, `MAX_MSG_LEN`, be placed in the config file and have all instances of constants representing message length be replaced.

**Comment by reallyly** [comment]
I wonder if this issue is still opened?  Because in https://github.com/goavki/phenny/blob/master/irc.py , at line 186, I saw a variable named `maxlength` to hold 430.  The only problem is that the  `maxlength` variable isn't in caps.

**Comment by wei2912** [comment]
Yes, it's not standardized across the modules that make use of the maximum
number of characters. That variable there is local and not a bot specific
constant.

**Comment by reallyly** [comment]
I'm interested to do this for a GCI task! :)

**Comment by jonorthwash** [comment]
Yes, please do! Also see my comment at https://github.com/goavki/phenny/issues/132#issuecomment-269710635 for an additional change that could accompany it.

**Comment by muhammad-mullboccus7** [comment]
should i do this?.....
@wei2912

**Comment by wei2912** [comment]
https://github.com/goavki/phenny/pull/240

@muhammad-mullboccus7 pick another task first, I think.

**Comment by wei2912** [comment]
This issue is now open for students to work on.
