### ISSUE TITLE
GitHub issue tracker marks an edited comment as a new comment

### ISSUE THREAD

**Issue by wei2912** [goavki/phenny#223]
An example of this behaviour:

 22:52      begiak| phenny: wei2912 * new comment on issue #223: Test comment. https://github.com/goavki/phenny/issues/223
 22:53      begiak| phenny: wei2912 * new comment on issue #223: Edited this comment. It was used for testing.                     https://github.com/goavki/phenny/issues/223

**Comment by wei2912** [comment]
Test comment.

**Comment by shardulc** [comment]
I would like to work on this for my [GCI task](https://codein.withgoogle.com/dashboard/task-instances/5381871124873216/). I assume this will have to be fixed for comments on issues, commits, and PRs?

**Comment by sushain97** [comment]
Yep.

**Comment by shardulc** [comment]
Should phenny:
 1. report that the comment was edited;
 2. show the text of the edited comment;
 3. show the changes to the comment;
 4. report the usual 'commenter, issue/commit/PR, url';
 5. or perform some combination thereof?

**Comment by wei2912** [comment]
1, 2, 4. 3 is overkill and would be spammy.
