### ISSUE TITLE
per-nick max-count on welcome message?

### ISSUE THREAD

**Issue by unhammer** [goavki/phenny#244]
There are people who seem to have `#apertium` in auto-join, but never say anything. It gets a bit old having the welcome message repeat for them ad infinitum – could begiak perhaps stop welcoming if they've been welcomed say 4 times? (Or just taper off a bit, like only welcome whenever their join_count is a round binary number `math.log(join_count,2) % 1 == 0` 😜)

**Comment by wei2912** [comment]
Tapering off would be a nice solution to this issue IMO.
