### ISSUE TITLE
identify each travis-ci error and create an issue for it

### ISSUE THREAD

**Issue by jonorthwash** [goavki/phenny#253]
We are currently getting [a number of errors reported for phenny](https://travis-ci.org/goavki/phenny/jobs/260824878) using travis-ci.  We need to categorise them all into issues so we can solve them one-by-one.

**Comment by muhammad-mullboccus7** [comment]
Ill try look into this..

**Comment by muhammad-mullboccus7** [comment]
Issues created successfully..
Links:
https://github.com/goavki/phenny/issues/263 
https://github.com/goavki/phenny/issues/266
https://github.com/goavki/phenny/issues/268 
https://github.com/goavki/phenny/issues/269
https://github.com/goavki/phenny/issues/270

**Comment by muhammad-mullboccus7** [comment]
Issues created successfully...
Links:
https://github.com/goavki/phenny/issues/263 
https://github.com/goavki/phenny/issues/266
https://github.com/goavki/phenny/issues/268 
https://github.com/goavki/phenny/issues/269 
https://github.com/goavki/phenny/issues/270
