### ISSUE TITLE
mail poller seems to have trouble with unicode message titles

### ISSUE THREAD

**Issue by jonorthwash** [goavki/phenny#260]
There are reports like

```
(22:00:12) begiak: apertium-stuff: =?UTF-8?B?SMOoY3RvciBBbMOycyBpIEZvbnQ=?= <h....@es....cat>: Re: Apertium-ca-ro
(22:00:16) begiak: apertium-turkic: Francis Tyers <ft...@pr....com>: =?utf-8?q?-KI=D0=B7_causative_in_Kazakh=3F?=
```

**Comment by Androbin** [comment]
This is not an error per se. This is expected behavior. See https://github.com/goavki/phenny/issues/155#issuecomment-164401429 for reference.
@unhammer Do we want to decode these characters nonetheless?

**Comment by shardulc** [comment]
It is an error because humans want to see the actual characters, not the email Unicode encoding.

**Comment by Androbin** [comment]
@shardulc "per se" as in "that IS the literal content of the email".
But as any "good" mail interface, we wanna translate that for users.

**Comment by jonorthwash** [comment]
> This is not an error 

No one said it was an error.  But it is an issue that should be fixed.

**Comment by Androbin** [comment]
@jonorthwash Wanna take a look at #298?
