### ISSUE TITLE
clock module is broken

### ISSUE THREAD

**Issue by jonorthwash** [goavki/phenny#261]
I implemented the quick hack in https://github.com/goavki/phenny/commit/6a2e593cd4c57db1c78a6f7e4629dbd1a3239cbb to make it not crash, but the problem needs to be fully debugged and addressed.

**Comment by jonorthwash** [comment]
I think this is related:
```
(00:41:35) firespeaker: .time Moscow
(00:41:36) begiak: firespeaker: Sorry, I don't know about the 'Moscow' timezone. Suggest the city on http://www.citytimezones.info
```

**Comment by Androbin** [comment]
Could you describe how to re-produce the crash (with the old code)?

**Comment by jonorthwash** [comment]
> how to re-produce the crash (without the quick hack)?

Start phenny.

I believe the scraper is failing.  We probably need another data source.

**Comment by Androbin** [comment]
```
git checkout 749a6b6ef3f7f43c1978d3e51586773cf95c5a18
./phenny
```

doesn't crash for me. Could you be more precise, please?

**Comment by jonorthwash** [comment]
Try checking out the parent commit, https://github.com/goavki/phenny/commit/749a6b6ef3f7f43c1978d3e51586773cf95c5a18

**Comment by Androbin** [comment]
See the tilde ~ ? It means "parent"

**Comment by jonorthwash** [comment]
Ah.  Hmm.  Could you simulate what happens if it gets a random web page instead of the one it's managing to get?

**Comment by Androbin** [comment]
I'll mock the URL and insert some logging.
