### ISSUE TITLE
test_login failed

### ISSUE THREAD

**Issue by muhammad-mullboccus7** [goavki/phenny#262]
line 614..
module failed: IRC module
test failed: test_login
""test_login (phenny.test.test_irc.BotTest) ... ERROR""
Heres the link: https://travis-ci.org/goavki/phenny/jobs/309867406

**Comment by shardulc** [comment]
@muhammad-mullboccus7 Here's the preferred format:

(Title: test_login failing for IRC module)

Failing test: [test_login](https://github.com/goavki/phenny/blob/master/test/test_irc.py#L39)
Failing module: [irc.py](https://github.com/goavki/phenny/blob/master/irc.py)
The error is on line 614 in [this build](https://travis-ci.org/goavki/phenny/jobs/309867406): ""test_login (phenny.test.test_irc.BotTest) ... ERROR"
