### ISSUE TITLE
Tests(2) failing for Testsearch module

### ISSUE THREAD

**Issue by muhammad-mullboccus7** [goavki/phenny#268]
https://travis-ci.org/goavki/phenny/jobs/309867406

Failing module: TestSearch
[https://github.com/goavki/phenny/blob/master/modules/test/test_search.py
](url)
 
- Failing test: test_gsearch 
     The error is on line 565 in this build: ""test_gsearch 
     (phenny.modules.test.test_search.TestSearch) ... ERROR"

- Failing test: test_suggest
     Also on line 567 in the same build:"test_suggest (phenny.modules.test.test_search.TestSearch) ... 
     ERROR"

Build log: https://travis-ci.org/goavki/phenny/jobs/309867406

**Comment by wei2912** [comment]
The module should be rewritten, as per the requirements outlined in https://github.com/goavki/phenny/issues/271.

**Comment by shardulc** [comment]
#325 fixes this.
