### ISSUE TITLE
Tests(6) failing for Bot module

### ISSUE THREAD

**Issue by muhammad-mullboccus7** [goavki/phenny#269]
Failing module: Bot.py

- Failing test: test_action
     The error is on line 613 in this build: ""test_action (phenny.test.test_irc.BotTest) ... ERROR"

- Failing test: test_login
     Also on line 614 in the same build:"test_login (phenny.test.test_irc.BotTest) ... ERROR"

- Failing test: test_msg
     Also on line 615 in the same build:"test_msg (phenny.test.test_irc.BotTest) ... ERROR"

- Failing test: test_msgflood
     Also on line 616 in the same build:"test_msgflood (phenny.test.test_irc.BotTest) ... ERROR"

- Failing test: test_notice
     Also on line 617 in the same build:"test_notice (phenny.test.test_irc.BotTest) ... ERROR"

- Failing test: test_ping
     Also on line 618 in the same build:"test_ping (phenny.test.test_irc.BotTest) ... ERROR"

Build log: https://travis-ci.org/goavki/phenny/jobs/309867406

**Comment by shardulc** [comment]
Fixed via #274.
