### ISSUE TITLE
test-locations failing for Weather module

### ISSUE THREAD

**Issue by muhammad-mullboccus7** [goavki/phenny#270]
Failing module: weather module (https://github.com/goavki/phenny/blob/master/modules/test/test_weather.py)

- Failing test: test_locations
     The error is on line 599 in this build: ""test_locations 
     (phenny.modules.test.test_weather.TestWeather) ... FAIL"

Build log: https://travis-ci.org/goavki/phenny/jobs/309867406

**Comment by Techievena** [comment]
Please assign me to this.

**Comment by Techievena** [comment]
We must add `*.db` to the `.gitignore` file. Unless the binary file gets added unnecessarily.

**Comment by shardulc** [comment]
Fixed via #274.
