### ISSUE TITLE
Have .more messages be (optionally) tagged

### ISSUE THREAD

**Issue by Androbin** [goavki/phenny#292]
See https://github.com/goavki/phenny/issues/259#issuecomment-354166715 for reference.

**Comment by wei2912** [comment]
it would be useful to store messages indexed by receiver (channel/user requesting command) and command called. Such an implementation should save the messages to a database.

**Comment by Androbin** [comment]
@wei2912 How about allowing the caller to pass any tag, not necessarily the command name, e.g. the module name?

**Comment by Androbin** [comment]
Waiting for #299.

**Comment by shardulc** [comment]
Another useful thing would be an admin method to clear the queue for a specific tag. (E.g. begiak gets a lot of git commits from a merge or something, and an admin decides they want to clear that queue without looking at all the commits because further commits are more important.)

**Comment by wei2912** [comment]
@Androbin That is possible, but the simplest solution IMO would be just the command name. A tag system may be overkill.

**Comment by wei2912** [comment]
@shardulc The current implementation pops the retrieved message from the queue upon each "call" of the command, which I think is sufficient, as the module isn't meant to deal with long lists of messages that need to be viewed. (If there are long lists of messages, a permanent pastebin should be provided instead.)

This is why I don't think the module should be used to, say, store git commit messages, as it may suppress essential information that is eventually lost. It should be used solely for the purpose of supplying extra information.

**Comment by Androbin** [comment]
@wei2912 Some commands can be called by more than one name.
How about we allow multiple tags and `SELECT [...] WHERE input IN tag` ?

**Comment by Androbin** [comment]
@wei2912 Some commands can be called by more than one name.
How about we allow multiple tags and `SELECT [...] WHERE input IN tag` ?

**Comment by shardulc** [comment]
> This is why I don't think the module should be used to, say, store git commit messages, as it may suppress essential information that is eventually lost.

@wei2912 Hmm, I thought the main reason we are using .more is to not spam the channel with messages precisely from modules like `git.py` or the `.queue` command, which tend to produce long and plentiful messages. When there are a bunch of git messages all at once they are not going to be "essential" as they form parts of a single change.

**Comment by Androbin** [comment]
@wei2912 Some commands can be called by more than one name.
How about we allow multiple tags and `SELECT [...] WHERE input IN tag` ?

**Comment by wei2912** [comment]
> @wei2912 Hmm, I thought the main reason we are using .more is to not spam the channel with messages precisely from modules like git.py or the .queue command, which tend to produce long and plentiful messages. When there are a bunch of git messages all at once they are not going to be "essential" as they form parts of a single change.

@shardulc hmm, fair point on having a bunch of git messages all at once. The more module is only designed to deal with a single piece of output, and not multiple. Such a retrieval system may be complicated to construct - does @Androbin have any ideas? Alternatively, I'd propose just putting those messages into a single message in the git module.

As for the queue command, it makes sense to use the more command, as you only need to store the last instance where the queue command was called.

(The fact that the more module can only deal with a single piece of output without becoming unwieldly means that it is probably best utilised for on-demand commands as opposed to hooks of any sort. An alternative system could be developed for hooks.)

**Comment by wei2912** [comment]
@Androbin You just need to store the messages by tagging the function that is executed with a specific identifier (since different aliases for the same command will eventually run that function).

**Comment by Androbin** [comment]
> The more module is only designed to deal with a single piece of output, and not multiple.

I have solved this two weeks ago in #277, merged in b4db977041c01b0ef369e36bd705964a53a8dc49.

**Comment by Androbin** [comment]
> You just need to store the messages by tagging the function that is executed with a specific identifier (since different aliases for the same command will eventually run that function).

The user may type either alias which means a given message has to be associated with both aliases.
