### ISSUE TITLE
Handle multiple time zones with same acronym

### ISSUE THREAD

**Issue by Androbin** [goavki/phenny#322]
See https://github.com/goavki/phenny/pull/315#issuecomment-354923469 for reference

**Comment by Androbin** [comment]
@shardulc Is there a good reason not to split the `dict` into `Abbreviation -> Offset` and `Country Code -> Offset` ? This would make things somewhat less complicated.

**Comment by shardulc** [comment]
I don't think I understand what you're suggesting. Can you give a short example of how the two `dict`s would work?

**Comment by Androbin** [comment]
And why don't we just remove the broken `citytimezones` code instead of just commenting it out?
I mean, what do we have version control for?

**Comment by Androbin** [comment]
Currently `phenny.tz_data` is `some_identifier -> offset`.
But `some_identifier` can be either an abbreviation like `PST` or a country name like `Ecudaor`.
Both are sourced from different Wikipedia sites/tables and are to be handled differently (e.g. this issue) but they are just thrown together into this one dict.

**Comment by Androbin** [comment]
I would split this dict into two separate dicts, one for each case.

**Comment by shardulc** [comment]
That would still not help the `.time PST` issue.

**Comment by Androbin** [comment]
Not directly, but since this requires changes to the data format, it would make it easier to have them separate.

**Comment by Androbin** [comment]
See, the issue only applies to the abbreviation case, not to the country name case.

**Comment by shardulc** [comment]
Suppose you did make the separate dicts. Then what happens when I call `.time PST`? I'm still not getting it.

**Comment by Androbin** [comment]
It would check both dicts and in the case of the abbreviation dict, it would retrieve a list of tuples `(full_name, offset)` while in the case of the country name dict, it won't find an matching offset.

**Comment by Androbin** [comment]
The problem mentioned is also known as ["Beware the Share"](http://programmer.97things.oreilly.com/wiki/index.php/Beware_the_Share).

**Comment by shardulc** [comment]
> in the case of the abbreviation dict, it would retrieve a list of tuples `(full_name, offset)`

Ah, so this is the part of your suggestion that actually fixes the issue. The separation of dicts is another matter.

**Comment by Androbin** [comment]
Actually, it's not that massive because of the separation.
In fact, it's that massive because fixing the issue required updating the logic on the rest of the code.
It was essentially copy-pasted code that just wanted to "get the next-best offset by name".
Since I didn't want to rewrite each copy, I've just put it in an extra function and just called that.

**Comment by Androbin** [comment]
Actually, it's not that big of a changeset because of the separation.

In fact, it's that big of a change set because fixing the issue required rewriting the writing to and reading from database and updating the logic of accessing the data in the rest of the code.

It was essentially copy-pasted code that just wanted to "get me an offset by name".
Since I didn't want to rewrite each copy, I've just put it in an extra function and just called that.

**Comment by Androbin** [comment]
By the way, "Beware the Share" regarding the structure, not use of the dicts.
