### ISSUE TITLE
updated begiak is screwed up with untested broken code

### ISSUE THREAD

**Issue by jonorthwash** [goavki/phenny#334]
When starting begiak cold, we now get this:

```
ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 224, in call
    try: func(phenny, input)
  File "/home/begiak/phenny/modules/git.py", line 380, in setup_server
    httpd = socketserver.TCPServer(("", PORT), Handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 224, in call
    try: func(phenny, input)
  File "/home/begiak/phenny/modules/git.py", line 380, in setup_server
    httpd = socketserver.TCPServer(("", PORT), Handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 224, in call
    try: func(phenny, input)
  File "/home/begiak/phenny/modules/git.py", line 380, in setup_server
    httpd = socketserver.TCPServer(("", PORT), Handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 224, in call
    try: func(phenny, input)
  File "/home/begiak/phenny/modules/git.py", line 380, in setup_server
    httpd = socketserver.TCPServer(("", PORT), Handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

We also get the following:

```
INFO: Nobody PONGed our PING, restarting
INFO: Closed!
WARNING: Disconnected. Reconnecting in 20 seconds...
```

Begiak then disconnects and reconnects.

@gstark0 @androbin

**Comment by gstark0** [comment]
I would say, the issue is in #330 :)

**Comment by Androbin** [comment]
@gstark0 No, this is an entirely different issue.
This is #133 which I have partly solved in #279.

**Comment by gstark0** [comment]
@Androbin Okay, no problem, this was just a guess, as I saw something was done with Ping-Pong :)

**Comment by Androbin** [comment]
For reference on the Ping-Pong topic, please see https://github.com/goavki/phenny/pull/330#discussion_r159740863.

**Comment by gstark0** [comment]
It's pretty weird, I don't see any issues running it locally.

**Comment by Androbin** [comment]
> It's pretty weird, I don't see any issues running it locally.

Please see the original issue. This error is about the port still "in use" from a previous run.

**Comment by Androbin** [comment]
To resolve this completely, `SO_REUSEADDR` may sometimes not be sufficient.

Be basically have two options here:
* Retry until the port has timed out
* Force the port to be released (with fire)

**Comment by Androbin** [comment]
There seem to be important differences between client and server sockets.
I think https://stackoverflow.com/a/18858817/4969370 should work for us.

**Comment by jonorthwash** [comment]
Nope, it's still in a join/part cycle, claiming this:
```
INFO: Nobody PONGed our PING, restarting
INFO: Closed!
```

**Comment by jonorthwash** [comment]
When it comes back, it says this:
```
ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 224, in call
    try: func(phenny, input)
  File "/home/begiak/phenny/modules/git.py", line 379, in setup_server
    httpd = PortReuseTCPServer(("", PORT), Handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/home/begiak/phenny/tools.py", line 65, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by jonorthwash** [comment]
Last night I saw something about too many open files before it stopped.

**Comment by Androbin** [comment]
I think I have figured why this still happens on all-cold restarts.
The issue is about some resources not **fully** released by the exit handler I installed.

**Comment by gstark0** [comment]
@Androbin Can we cause the error locally? For testing purpose, it would help debugging it.

**Comment by jonorthwash** [comment]
As before:
```
POLLED
INFO: Nobody PONGed our PING, restarting
INFO: Closed!
WARNING: Disconnected. Reconnecting in 20 seconds...
```
```
INFO: connected!
ERROR: Traceback (most recent call last):
  File "/home/begiak/phenny/bot.py", line 224, in call
    try: func(phenny, input)
  File "/home/begiak/phenny/modules/git.py", line 379, in setup_server
    httpd = PortReuseTCPServer(("", PORT), Handler)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/home/begiak/phenny/tools.py", line 65, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by Androbin** [comment]
This is expected since the last change is about the exit of the previous instance.
It should however release the port from now on and get rid of that error.

**Comment by Androbin** [comment]
However, I don't yet know how the Ping-Pong issue relates to the port issue.

**Comment by gstark0** [comment]
@Androbin Well, I thought it did, but after fixing the pong issue, I noticed it doesn't matter. In fact, the only solution I see about the port issue is killing it through subprocess.

**Comment by Androbin** [comment]
Actually, the call to `shutdown` that was missing should force the port to be released by instances referencing it and the call to `close` de-allocates it completely.

**Comment by gstark0** [comment]
@Androbin You mean #346 ? It doesn't solve port problem unfortunately :(

**Comment by Androbin** [comment]
The only possibility left is that the `atexit` handler is not executed on termination.

**Comment by Androbin** [comment]
The callback is not called when the program dies because of a signal btw.
@gstark0 I suspect you used `Ctrl + C` or similar to quit?

**Comment by Androbin** [comment]
@gstark0 I suspect you used `Ctrl + C` or similar to quit?
@jonorthwash How exactly do you kill the old instance?

**Comment by gstark0** [comment]
@Androbin Yes, I use Ctrl+C, we can after every Begiak run just kill the previous instance so the port will be free, but it's not what we want here. Let's just make it killing it with every run.

**Comment by jonorthwash** [comment]
> How exactly do you kill the old instance?

It never was killed.  It just disconnected and tried to reconnect.  I guess it tried to restart itself, but was running in the same process.  In the case of multiple messages about the port being open, it's possible there were multiple [crashed?] versions of the code running.

**Comment by jonorthwash** [comment]
Aha!  When I `^C` it, I don't get multiple port-in-use errors.  When I kill it with start-stop-daemon, on next start it does give multiple port-in-use messages.

**Comment by Androbin** [comment]
Okay, so we have narrowed down the problem.

**Comment by Androbin** [comment]
@jonorthwash I have added some more patches to #351 which should fix some breakpoints.

**Comment by gstark0** [comment]
#350 Also
