### ISSUE TITLE
Tests failing for lastfm.py module

### ISSUE THREAD

**Issue by gstark0** [goavki/phenny#335]
Sometimes some functions in test_lastfm return errors:

`[Errno 110] Connection timed out'`

**Comment by Androbin** [comment]
Let's continue with #343 ?

**Comment by gstark0** [comment]
Irrelevant, but if you want, we can move there, nice to see it's more general issue.

**Comment by Androbin** [comment]
Your case may also suffer from #345.

**Comment by Androbin** [comment]
This can be closed as duplicate.
