### ISSUE TITLE
Handle connection timeouts for all unit tests

### ISSUE THREAD

**Issue by Androbin** [goavki/phenny#343]
Sometimes tests request data but either the connection or the build time out (after half an hour).
We should consider setting a limit on how much time a test may take.
Then we can either skip the test or declare it failed.

**Comment by Androbin** [comment]
If possible, implementing #345 is preferable.

**Comment by Androbin** [comment]
Alternatively, set timeouts directly to all connections.

**Comment by Androbin** [comment]
@gstark0 /cc

**Comment by shardulc** [comment]
With #347 I think this can be closed?
