### ISSUE TITLE
Add missing is_up tests

### ISSUE THREAD

**Issue by Androbin** [goavki/phenny#345]
For example: `test_iso639` or other tests for modules which scrape data.

**Comment by gstark0** [comment]
What's wrong with test_search?

**Comment by Androbin** [comment]
See [travis/325602916#L688](https://travis-ci.org/goavki/phenny/jobs/325602916#L688) for reference.
If a `is_up` check is already in place, it may be that is is not short after the check.
In this case, see #343 for a catch-them-all solution.

**Comment by Androbin** [comment]
Also see tests for the `calc`, `head`, `iso639` and `posted` modules.

**Comment by gstark0** [comment]
@Androbin calc module doesn’t use any network functions, it’s fully local

**Comment by gstark0** [comment]
hmm actually this python interpreter is online function, not sure if it works tho

**Comment by Androbin** [comment]
Closing with #347
