### ISSUE TITLE
.time spams whole chat now

### ISSUE THREAD

**Issue by gstark0** [goavki/phenny#360]
@shardulc @sushain97 
Using `.time` command will spam whole chat, if this is intended, it's super useless IMHO :
<img width="592" alt="screen shot 2018-01-09 at 07 20 51" src="https://user-images.githubusercontent.com/25964807/34707468-fdcf2558-f50d-11e7-90ad-b04b73caa1be.png">
<img width="513" alt="screen shot 2018-01-09 at 07 20 43" src="https://user-images.githubusercontent.com/25964807/34707473-ff54c5ea-f50d-11e7-8d33-5622872b224c.png">

**Comment by Himanshu40** [comment]
According to me, it doesn't need to send multiple lines if there are multiple hits and it should send one long line. Looks like `.time GMT` shows all possible GMTs.

**Comment by gstark0** [comment]
Yes, why sending all GMT's? If I want GMT+6 I can just specify it.

**Comment by Himanshu40** [comment]
@gstark0  yeah you are right .`time GMT+6` calling all possible GMTs. Looks like it should send one

**Comment by gstark0** [comment]
<img width="540" alt="screen shot 2018-01-09 at 07 35 05" src="https://user-images.githubusercontent.com/25964807/34707800-adb36bd6-f50f-11e7-81db-5d4cfa968b41.png">
<img width="512" alt="screen shot 2018-01-09 at 07 35 14" src="https://user-images.githubusercontent.com/25964807/34707804-af79cf6e-f50f-11e7-9bca-3e8f4bcf73b4.png">

**Comment by Himanshu40** [comment]
so `.time` may send output only once with a long line or it should show only output not less than 3 to avoid spamming

**Comment by sushain97** [comment]
Yeah, this really needs to be fixed. @Androbin ?

**Comment by sushain97** [comment]
I think we can sort the lines matched and output the top 3.

**Comment by gstark0** [comment]
@sushain97 Can I take a look at his?

**Comment by sushain97** [comment]
Sure.

**Comment by Androbin** [comment]
"GMT" printing all of "GMT" is due to a rash design decision.
"GMT+X" printing more than one line is a bug.
For the latter, I don't know where the issue could be.

**Comment by Androbin** [comment]
I may clarify that for abbreviations with multiple possible expansions, the full name is printed, but the latter is not added to either dictionary. Bad design decision.

**Comment by Androbin** [comment]
We could change this line from "GMT" to "GMT+0":
https://github.com/goavki/phenny/blob/master/modules/clock.py#L169

**Comment by Androbin** [comment]
It seems like ABC+X gets the +X part stripped before lookup.

**Comment by Androbin** [comment]
How do we want to handle such cases?

**Comment by sushain97** [comment]
Output up to 3 and be more intelligent about the matching?

**Comment by Androbin** [comment]
* Putting a limit on the number of matches 👍
* Being more intelligent about matching ❓

See my last comment on which code interferes with this.

**Comment by sushain97** [comment]
Change the code then? I don't understand what the problem is.

**Comment by Androbin** [comment]
The problem is that we want to handle `+/-X` in two different ways.
The simplest solution would of course be to drop the old feature.

**Comment by sushain97** [comment]
What exactly is the old feature?

**Comment by Androbin** [comment]
It extends the `+/-X` syntax to any timezone.
But it interferes with the scraped `+/-X` entries.

**Comment by sushain97** [comment]
I see. Why can't we only allow that syntax when it helps to provide a more
meaningful result?

On Jan 17, 2018 10:23 AM, "Robin Richtsfeld" <notifications@github.com>
wrote:

It extends the +/-X syntax to any timezone.
But it interferes with the scraped +/-X entries.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/goavki/phenny/issues/360#issuecomment-358358328>, or mute
the thread

**Comment by Androbin** [comment]
Maybe we can get around this with #378.
