### ISSUE TITLE
\x15\x03\x01 invalid response in test_slogan

### ISSUE THREAD

**Issue by Androbin** [goavki/phenny#367]
See https://travis-ci.org/goavki/phenny/jobs/326923804#L650 for reference
This happens from time to time and seems to be a SSL-related issue.
I don't yet know why this doesn't happen consistently.

**Comment by gstark0** [comment]
You have SSL enabled?

**Comment by Androbin** [comment]
> You have SSL enabled?

It's the Travis build, like I said.
The `default.py.example` has `ssl = False` in it.
And this should not even be read by `nosetests3`.

**Comment by Androbin** [comment]
> This happens from time to time and seems to be a SSL-related issue.

It's about the SSL of the server, by the way.

**Comment by gstark0** [comment]
hmmm, so we can only handle the error, thats all

**Comment by Androbin** [comment]
We should probably just skip the test in such case.
But I don't know which other tests might be affected.
And should we hardcode "\x15\x03\x01" or is there a more general pattern?

**Comment by gstark0** [comment]
@Androbin I think we should hardcode this, as this is specific for SSL problem. More general pattern could include some encodings also, which we don't want.

**Comment by shardulc** [comment]
@gstark0 @Androbin Where do the "\x15\x03\x01" characters come from? If we're reasonably sure that they are always the same characters, we can merge #370.

**Comment by Androbin** [comment]
I was unable to find official documentation for \x15\x03\x01 or the like.

Thousands of other parties talk about either:
* "\x16\x03\x01"
* "\x15\x03\x01" followed by "\x00\x02\x02"

Either way, we seem to get only this one.

**Comment by shardulc** [comment]
Hmm. I guess #370 can only help then.

**Comment by Androbin** [comment]
As far as I understand, it is the result of either a
* malformed HTTP request
* malformed HTTP response

**Comment by gstark0** [comment]
@shardulc basically, it seems like we’re getting this error only, and it is related to SSL somehow. Although we could make more general pattern in case any other of these appeared, but this pattern is also responsible for some encodings which may occur, so it would better to just skip this particular case.
